### PR TITLE
Use `OnceExit` to ensure hashing is done after other plugins

### PR DESCRIPTION
**Pull request by koddsson**
The PostCSS docs are pretty minimal, but I think this will fix an issue I was having where PostCSS would do hashing on un-minified CSS files, and then it would minify, causing hash mismatches in my project.

https://postcss.org/api/#plugin-onceexit

### CODE REVIEW

**Review by keithamus — APPROVED** [review]

**Comment by keithamus** [comment]
@dacodekid would you be able to give @koddsson commit access to this repo? @koddsson is a colleague of mine and we’re both working on this package now.

**Comment by dacodekid** [comment]
@keithamus .. just sent a `Collaborator` invitation to @koddsson.  If would prefer, I don't mind change this repo's ownership to yourself as well.  Plz let me know.

**Comment by keithamus** [comment]
Might be easier so I can administer it easier, but I don't want to steal the credit for the great work you did! Up to you 😜

**Comment by dacodekid** [comment]
Not at all.  Haven't done anything like it before.  Let me search it through and will start the process immediately.

**Comment by dacodekid** [comment]
image

When I tried, getting this error. Not sure what to do here :(

**Comment by keithamus** [comment]
That'll be my fork. I've just deleted it so it should be good to go now!

**Comment by dacodekid** [comment]
@keithamus transfer request has been sent.  Should I do this for `npm` as well ?

**Pull request merged**
